# This is a basic workflow to help you get started with Actions

name: Variable substitution.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Organice project
  setup-app:
    if: github.ref == 'refs/heads/main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cloning repo.
        uses: actions/checkout@v2

      # https://docs.github.com/en/developers/webhooks-and-events/github-event-types
      - name: Debug.
        run:
          echo ${{ github.event }}
          echo ${{ github.event }}
          echo ${{ github.event }}
          echo ${{ github.event }}

      - name: Selecting app.
        env:
          SELECTED_APP: fastapi-app
        run: |
          mkdir ./selected-app
          mv ./templates/$SELECTED_APP/* ./selected-app

      - name: Replace variables.
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          find ./ -type f -exec sed -i "s/REPO_NAME/$REPO_NAME/g" {} +

      - name: Cleanup.
        run: |
          find ./ -maxdepth 1 -regextype posix-extended  -not -regex "./.git|./|./selected-app" -exec rm -fr {} +
          mv ./selected-app ./
          rm -fr ./selected-app

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v1
